In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
# print("hello")
from numpy.linalg import eigvals
import matplotlib.pyplot as plt
from numpy.linalg import eigh

In [2]:
# Load CSV file into a numpy array
data = np.genfromtxt('data/ex2.csv', delimiter=';')

# Print the data
print(data)


[[ 1.  1.  3.]
 [-1. -1.  3.]
 [ 1.  1. -3.]
 [-1. -1. -3.]
 [ 1. -1.  0.]
 [-1.  1.  0.]]


In [3]:
object= StandardScaler()
scale = object.fit_transform(data) 
print(scale)


[[ 1.          1.          1.22474487]
 [-1.         -1.          1.22474487]
 [ 1.          1.         -1.22474487]
 [-1.         -1.         -1.22474487]
 [ 1.         -1.          0.        ]
 [-1.          1.          0.        ]]


In [4]:
RX = np.corrcoef(scale, rowvar=False)

print(RX)

[[1.         0.33333333 0.        ]
 [0.33333333 1.         0.        ]
 [0.         0.         1.        ]]


In [5]:


spectrum = eigvals(RX)

print(spectrum)

[1.33333333 0.66666667 1.        ]


In [6]:


eigenvalues, eigenvectors = eigh(RX)


In [7]:

print("eigenvalues")
print(eigenvalues)

eigenvalues
[0.66666667 1.         1.33333333]


In [8]:

print("eigenvectors")
print(eigenvectors)

eigenvectors
[[-0.70710678  0.          0.70710678]
 [ 0.70710678  0.          0.70710678]
 [ 0.          1.          0.        ]]


In [9]:

CX = eigenvectors.T.dot(scale.T).T
print(CX)

[[ 0.          1.22474487  1.41421356]
 [ 0.          1.22474487 -1.41421356]
 [ 0.         -1.22474487  1.41421356]
 [ 0.         -1.22474487 -1.41421356]
 [-1.41421356  0.          0.        ]
 [ 1.41421356  0.          0.        ]]


In [10]:
# plt.plot(range(1, len(spectrum) + 1), spectrum, 'o-')
# plt.xlabel('Component')
# plt.ylabel('Eigenvalue')
# plt.title('Scree Plot')
# plt.show()

In [11]:
# Determine the number of principal components to retain
cumulative_variance = np.cumsum(spectrum) / np.sum(eigenvalues)
print("Cumulative variance:", cumulative_variance)
n_components = np.argmax(cumulative_variance >= 0.95) + 1
print("Number of principal components to retain:", n_components)

Cumulative variance: [0.44444444 0.66666667 1.        ]
Number of principal components to retain: 3
